name: emasm
channels:
  - defaults
dependencies:
  - h5py
  - numpy
  - pip
  - scipy
  - pytest
  - hypothesis
  - networkx
  - matplotlib
  - scikit-image
  - python-snappy
  - pip:
    - czifile
    - --editable ../../recon # is executed in ./.snakemake/conda