
% load_files = {
%   '/home/watkinspv/Data/efpl/efpl_paper_interp_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_paper_interp_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_agglo_rf_75iter2p_reduced_interp_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_agglo_rf_75iter2p_reduced_interp_norandbg.mat'
% };
% load_indices = [1 2 1 2]; 

% load_files = {
%   '/home/watkinspv/Data/efpl/efpl_paper_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_paper_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_agglo_rf_75iter2p_reduced_norandbg.mat'
%   '/home/watkinspv/Data/efpl/efpl_agglo_rf_75iter2p_reduced_norandbg.mat'
% };
% load_indices = [1 2 1 2]; 

load_files = {
  '/home/watkinspv/Data/efpl/efpl_paper_interp_norandbg.mat'
  %'/home/watkinspv/Data/efpl/efpl_huge_xyzonly_offset_interp_norandbg.mat'
  '/home/watkinspv/Data/efpl/efpl_huge_xyzonly_offset_interp_norandbg.mat'
  '/home/watkinspv/Data/efpl/efpl_huge_xyzonly_offset_interp_norandbg.mat'
};
load_indices = [2 2 3]; 






% load from different saved .mat files generated by knossos_efpl
nload = length(load_indices); o = cell(1,nload); pdata = cell(1,nload);
for i = 1:nload
  X = load(load_files{i});
  o{i} = X.o{load_indices(i)}; pdata{i} = X.pdata(load_indices(i));
  % mehlab
  %if i==1, pdata = X.pdata(load_indices(i)); else pdata(i) = X.pdata(load_indices(i)); end
end





% plot paramters
pplot = struct;

% for normal pdfs
% fixed width bins
pplot.dplx = 0.0001; pplot.plx = -1.9+pplot.dplx/2:pplot.dplx:2.2-pplot.dplx/2; pplot.nplx = length(pplot.plx);
%pplot.dplx = 0.0005; pplot.plx = -1.9+pplot.dplx/2:pplot.dplx:2.2-pplot.dplx/2; pplot.nplx = length(pplot.plx);
%pplot.dplx = 0.05; pplot.plx = -1.9+pplot.dplx/2:pplot.dplx:2.2-pplot.dplx/2; pplot.nplx = length(pplot.plx);
%pplot.dplx = 0.075; pplot.plx = -1.925+pplot.dplx/2:pplot.dplx:2.2-pplot.dplx/2; pplot.nplx = length(pplot.plx);
%pplot.dplx = 0.1; pplot.plx = -1.9+pplot.dplx/2:pplot.dplx:2.2-pplot.dplx/2; pplot.nplx = length(pplot.plx);
% variable bins
%pplot.dplx = linspace(0.0005,0.05,163); pplot.plx = cumsum(pplot.dplx)-1.9; pplot.nplx = length(pplot.plx);
%pplot.dplx = linspace(0.0001,0.05,164); pplot.plx = cumsum(pplot.dplx)-1.9; pplot.nplx = length(pplot.plx);

% for roc analysis
pplot.dplxs = 0.0001; pplot.plxs = -1.9+pplot.dplxs/2:pplot.dplxs:2.2-pplot.dplxs/2; pplot.nplxs = length(pplot.plxs);

% for node histograms
%pplot.dndx = 1; pplot.ndx = 0+pplot.dndx/2:pplot.dndx:150-pplot.dndx/2; pplot.nndx = length(pplot.ndx);
pplot.dndx = 5; pplot.ndx = 0+pplot.dndx/2:pplot.dndx:2000-pplot.dndx/2; pplot.nndx = length(pplot.ndx);

%pplot.param_name = 'thresholds';
pplot.param_name = '';
pplot.dxticksel = 3;

pplot.baseno = 2000;

po = knossos_efpl_plot(pdata,o,pplot);


