name: Test with pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Modify envrionment.yml for github-actions
      run: |
        sed -i 's+../../+./+g' environment.yml
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
          activate-environment: emasm
          environment-file: ./environment.yml
          auto-activate-base: false
          shell: bash -l {0}
    - name: Test with pytest
      shell: bash -l {0}
      run: pytest
